### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [csgrimes1/pg-provision#1]
about this code: https://github.com/csgrimes1/pg-provision/blob/42593a6cf7b77277c4cd155cfe1b6f2a372fd5e5/js/run-updates.js

Have another look at [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started): 

Your first call takes initialization options, you second one takes database connection parameters. Instead, you pass in connection details as if initialization options, which will yield no good result ;)

**Comment by csgrimes1** [comment]
I was just stubbing things in and haven't written any working code or tests
yet. I have used your library before, and I won't have any problems getting
the database stuff working.

Thanks,
Chris

**Comment by vitaly-t** [comment]
n.p.
